# Generated by Django 4.1.3 on 2022-11-15 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookies_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='user_name',
            new_name='username',
        ),
    ]
